### ISSUE TITLE
Support `query` template tag

### ISSUE THREAD

**Issue by pluma** [monotykamary/vscode-aql#1]
This plugin works great when using the `aql` template tag, but it doesn't currently recognise the `query` template tag in Foxx/arangosh (`require("@arangodb").query`), which executes the given AQL query directly.

I'm not familiar with the VS Code syntax format, but I think this would just require adding "query" as an alternative here:

https://github.com/monotykamary/vscode-aql/blob/master/syntaxes/inline-aql.json#L21

I'm not sure matching for `AQL` in that spot is really necessary, btw. Is that in case someone renames the template tag to uppercase?

**Comment by monotykamary** [comment]
> This plugin works great when using the aql template tag, but it doesn't currently recognise the query template tag in Foxx/arangosh (require("@arangodb").query), which executes the given AQL query directly.

Oh woops, I completely forgot about that 😬. I've made a pull request for the query helper in which I'll merge in a bit.

> I'm not familiar with the VS Code syntax format, but I think this would just require adding "query" as an alternative here:
>
>https://github.com/monotykamary/vscode-aql/blob/master/syntaxes/inline-aql.json#L21

Yep yep, that's correct; just need to add another alternate entry for it - incredibly simple to add on 😊

> I'm not sure matching for AQL in that spot is really necessary, btw. Is that in case someone renames the template tag to uppercase?

I'm not too sure myself if it's needed. I noticed dothebart using an uppercase prefix for it, so I figured someone out there might be using it.

**Comment by pluma** [comment]
Nice. The plugin works fine now:

![image](https://user-images.githubusercontent.com/1280922/69324339-8febdf00-0c48-11ea-84bd-5b612d58aef5.png)
