### ISSUE TITLE
How to activate the plugin in Golang?

### ISSUE THREAD

**Issue by Delicious-Bacon** [monotykamary/vscode-aql#18]
Golang does not support "tags" in front of string literals, so doing this is invalid:
```
q := aql`FOR doc IN...`
```

However, these would be valid, but these don't activate the extension:
```
// prepend block comment before string literal
q := /*aql*/`FOR doc IN...`  

// append line comment into string literal
q := `//aql
    FOR doc IN...`

// append block comment into string literal
q := `/*aql*/FOR doc IN...`
```

**Comment by monotykamary** [comment]
At the moment, the extension currently supports .js, .jsx, .ts, .tsx files. I'll see if I can whip up support for Golang.

**Comment by monotykamary** [comment]
I've added support for Golang in `v1.7.0`. There is a slight bug with template literals when using `//aql`, which I should probably get around to fixing. I recommend using the `/*aql*/` block comment variant instead.

![image](https://user-images.githubusercontent.com/1130103/183252544-c2797889-e35c-4cd5-8919-b4aefa724fa4.png)

**Comment by Delicious-Bacon** [comment]
Hey, @monotykamary !

Thank you for the prompt solution! ❤️ 💯 

Block comment variant it is then! 😄

**Comment by Neicul123** [comment]
Just in case anyone else struggles with getting the aql highlighting to work:
The Go vscode plugin recommends to enable gopls's semanticTokens setting. With this enabled the aql highlighting won't show up 😓 

I got it to show up by either disabling the setting, or leaving it enabled and putting `ui.noSemanticString` to false (this seems like the way to go).

Thanks for your hard work @monotykamary !
